### PR TITLE
Try fixing plot issues

### PR DESCRIPTION
**Pull request by nbenn**

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
I compared with main where I have `Error in ensym: Can't convert to a symbol`, @nbenn and I get the plot without error. However, if I change the data, it crashes the app. My code:

```r
library(ggplot2)
devtools::load_all()

num_cols <- function(data) {
  colnames(dplyr::select_if(data, is.numeric))
}

num_cols <- function(data) {
  colnames(dplyr::select_if(data, is.numeric))
}

new_ggscatterstats_block <- function(data, ...) {
  types <- c(
    "parametric",
    "nonparametric",
    "robust",
    "bayes"
  )

  new_block(
    expr = quote(
      ggstatsplot::ggscatterstats(
        x = .(x),
        y = .(y),
        type = .(type),
        conf.level = .(conf.level)
      )
    ),
    fields = list(
      x = new_select_field(num_cols(data)[1], num_cols(data)),
      y = new_select_field(num_cols(data)[2], num_cols(data)),
      type = new_select_field(types[1], types),
      conf.level = new_numeric_field(0.95, min=0, max=1)
    ),
    class = c("ggscatterstats_block", "plot_block")
  )
}

ggscatterstats_block <- function(data, ...) {
  initialize_block(new_ggscatterstats_block(data, ...), data)
}

blockr::register_block(
  constructor = ggscatterstats_block,
  name = "scatter plot",
  description = "scatter with stats",
  classes = c("ggscatterstats_block", "plot_block"),
  input = "data.frame",
  output = "data.plot"
)

stack <- new_stack(
  data_block
)

ui <- fluidPage(
  theme = bslib::bs_theme(version = 5),
  add_block_ui(),
  generate_ui(stack)
)

server <- function(input, output, session) {
  nb <- eventReactive(input$add, {
    list(
      block = block <- available_blocks()[[input$selected_block]],
      position = NULL
    )
  })
  generate_server(stack, new_block = nb)
}

shinyApp(ui, server)
```

**Review by DivadNojnarg — APPROVED** [review]
Appart from the data update issue, this does not seem to break other features.

**Comment by nbenn** [comment]
@DivadNojnarg so I merged this. While checking what was going on for a data switch, what worries me a bit is that downstream validators are not being called to handle the issue. No idea why and how big of a problem this is.

**Comment by JohnCoene** [comment]
@nbenn well done there, works like a charm!

**Pull request merged**
