### PR TITLE
Rework computation authorization between blocks

### LINKED ISSUE #55: Reactivity inconsistencies in generate_server.transform_block
```r
o <- observeEvent(
        eval(obs_expr(blk())),
        secure(eval(set_expr(blk()))),
        ignoreInit = TRUE
      )
```

This gets triggered too many times. Hashing inputs shows that the third event should not trigger. 

```bash
[1] "35f073918d0c815bbf81af029fa4a3f8"
Called from: observe()
Browse[1]> c
[1] "e36cc6a7ecb1cc806c044ad143937f7a"
Called from: observe()
Browse[1]> c
[1] "e36cc6a7ecb1cc806c044ad143937f7a"
Called from: observe()
Browse[1]>
```

Also, I don't think we should allow this expression to run without checking that the block input state is compatible with the received data. For instance, assuming input values refer to columns not available in the `in_dat()`...

```r
out_dat <- reactive({
   evaluate_block(blk(), data = in_dat())
})
```

### PR DESCRIPTION
**Pull request by DivadNojnarg**
Will fix #55 and #33.

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
@JohnCoene : for now validation is not added to the data and plot block (only transform blocks). If you want to have it in all blocks, let me know.

**Comment by JohnCoene** [comment]
Currently I get `Error in module: object 'InputValidator' not found`

**Comment by DivadNojnarg** [comment]
When the block is invalid and collapsed, we add an extra border class to signal that something is wrong in this block.
Screenshot 2023-10-27 at 10 34 43

**Comment by DivadNojnarg** [comment]
Closing as implemented in another PR.

**Pull request closed without merging**
