### PR TITLE
Rearrange buttons on block UI

### PR DESCRIPTION
**Pull request by JohnCoene**
This rearranges buttons on block UI so it looks like it did originally: placing the buttons on the top right.

Note that now that the code block is within the body of the block the button cannot be shown when the block is collapsed.

### CODE REVIEW

**Review by DivadNojnarg — COMMENTED** [review]
Thanks @JohnCoene. I am ok with the show code not always visible.

Few requests:

- Can we change the collapse icon to look like more https://fontawesome.com/icons/chevron-up?f=classic&s=solid and https://fontawesome.com/icons/chevron-down?f=classic&s=solid dynamically. 
- Can we add a tooltip for each button ("Show code", "Collapse block", ...)?

Same at the stack level:

- Replace the edit button by a dynamic collapse button. 
- Show a tooltip on the code icon.

**Comment by JohnCoene** [comment]
Updated icons.
Just added tooltip to copy code button on stack, block already has `data-bs-toggle` so it's a bit more work and I have other more urgent things to tackle before.

**Review by DivadNojnarg — CHANGES_REQUESTED** [review]
Thanks for adding the new icons. There seem to be an inconsistency from a block to another (see below): 2 blocks in the same state but the icon isn't the same.
Screenshot 2024-01-04 at 16 54 37

**Comment by JohnCoene** [comment]
I cannot reproduce this, can you tell how you got to that?

**Comment by JohnCoene** [comment]
Reproduced, fixed in last commit

**Review by DivadNojnarg — APPROVED** [review]
Thanks. LGTM.

**Pull request merged**
