### PR TITLE
fix: collpase body placed in header #136

### PR DESCRIPTION
**Pull request by JohnCoene**
This addresses some of the issues in #136 

We're still missing the code output at the block level, I'm not sure why this was removed.

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
Thanks for checking this. The collapse triggers should be located as shown below in red. The idea was to have the collapse trigger and the collapsible element in the same function for easier customisation (before we had all the triggers in the block head and the collapsible targets in different components). Do you mind changing the icon so they look like collapse triggers? I kept the original icon as they were in the first iteration but now this is misleading. Feel free to improve the design if you wish so we have a better separation between the code output and the block main output. 

292256518-374336e5-71be-4a32-8987-739f8cca004e

I'll review when I am back next Wednesday.

**Comment by JohnCoene** [comment]
OK, I did not know we were changing all the UI.

It's currently very confusing.

**Comment by DivadNojnarg** [comment]
Side note: code to add the collapse code button within the header from the stack method. This however re-introduces the decoupling issue we had before (trigger and target in 2 different pieces of code, introducing some fragility if people had to customise the block_body or block_code methods). 

```r
# within generate_ui.stack

collapse_code_id <- htmltools::tagQuery(tmp)$
            find(".block-code")$
            selectedTags()[[1]]$
            attribs$id

          # Remove button now belongs to the stack namespace!
          htmltools::tagQuery(tmp)$
            find(".block-tools")$
            prepend(
              list(
                tags$a(
                  class = "text-decoration-none block-output-toggle",
                  href = sprintf("#%s", ns("outputCollapse")),
                  iconOutput()
                ),
                tags$a(
                  class = "text-decoration-none block-code-toggle",
                  `data-bs-toggle` = "collapse",
                  href = sprintf("#%s", collapse_code_id),
                  `aria-expanded` = "false",
                  `aria-controls` = collapse_code_id,
                  iconCode()
                ),
                block_remove(b, ns(sprintf("remove-block-%s", block_id)))
              )
          )$
          allTags()
```

**Comment by JohnCoene** [comment]
@DivadNojnarg I cannot see this snippet in main

**Comment by DivadNojnarg** [comment]
That's something I checked this morning but did not push. I keep it here to remember for later, if we use it.

**Pull request closed without merging**
