### PR TITLE
Dynamic removal of blocks

### PR DESCRIPTION
**Pull request by DivadNojnarg**
Will fix one of the issue in #136, where the remove button is missing for dynamically added blocks.

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
@nbenn : unit tests will follow in another PR. I already have some of them in #119 and don't want to copy and paste here.

**Comment by DivadNojnarg** [comment]
Note @nbenn: I can also make `handle_remove_block` an internal function instead of S3, if we assume people won't need to customise it, which is likely.

**Comment by nbenn** [comment]
> Note @nbenn: I can also make `handle_remove_block` an internal function instead of S3, if we assume people won't need to customise it, which is likely.

@DivadNojnarg You could also not export the generic function itself I believe. The corresponding (class-specific) methods have to be exported, but as long as the generic is not, it should behave as "interal" function, despite using s3 dispatch.

**Review by nbenn — COMMENTED** [review]
No objections from my side.

**Comment by DivadNojnarg** [comment]
Great. I am done with this PR. This can go to main.

**Review by nbenn — APPROVED** [review]
Lgtm.

**Pull request merged**
