### PR TITLE
Bug/accidental remove handle remove block

### PR DESCRIPTION
**Pull request by christophsax**
@DivadNojnarg does that fix https://github.com/blockr-org/blockr/issues/173?

### CODE REVIEW

**Review by DivadNojnarg — COMMENTED** [review]
I can delete/add blocks. What was the reason to remove the validation?

**Comment by JohnCoene** [comment]
Validation and the improvements we made to it seem indeed to be gone.
Also seems to have broken some rendering of blocks where we render collapsed to only show last output.

**Comment by christophsax** [comment]
No reason to remove validation. That was a shortcut I did during development. Will re add it.

**Comment by christophsax** [comment]
@JohnCoene will push a fix for the validation in half an hour.

Can you give me an example for the rendering issues?

Sorry for the trouble, but my PR enables us to follow up with a range of useful blocks so I would be happy if we don't have to revert.

**Comment by DivadNojnarg** [comment]
@christophsax: what about keeping your changes but restoring the old `generate_server` methods as we had before and making the code depend on them again. This will give space to follow up and make sure everything runs smoothly when ready.

**Comment by JohnCoene** [comment]
Is #178 related to this?

**Comment by christophsax** [comment]
@DivadNojnarg, replacing the old `generate_server` methods (for blocks) was the central piece of the PR. I haven't intended to touch the method for the stack. If you want to revert the methods for the blocks, we probably should revert everything.

But I think this PR resolves most of the problems, doesn't it?

**Review by nbenn — APPROVED** [review]
Lgtm.

**Pull request merged**
