### PR TITLE
Improve data loading block

### PR DESCRIPTION
**Pull request by DivadNojnarg**
See #148, #149.

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
TO DO:
- find a way to allow user to pass in different browsable folders with the `filesbrowser_field`. Right now, I hardcoded it to `volumes <- c(home = path.expand("~"))` for testing.

**Comment by DivadNojnarg** [comment]
@nbenn : as I couldn't make any of the upload/filebrowser field properly render within `variable_field`, we temporarily have 2 handle 2 blocks (1 block containin the 2 field would be too messy). That should be good enough for basic usage though.

**Comment by DivadNojnarg** [comment]
I noticed `ignoreInit = TRUE` is causing any subsequent block to `upload_block` not to update properly (have to re-upload data). That refers to one of my comment in #148.

**Comment by christophsax** [comment]
@DivadNojnarg re `ignoreInit = TRUE`, are you referring to this? #196 seems good to me, but not sure if we overlooked something.

**Pull request merged**
