### PR TITLE
Icon toggle

### PR DESCRIPTION
**Pull request by JohnCoene**
This fixes the icon toggle and the initialisation of new blocks

### CODE REVIEW

**Comment by DivadNojnarg** [comment]
I just noticed something weird with the delete button.

https://github.com/blockr-org/blockr/assets/18291543/766505a5-a00c-4aa4-9392-53a82fd03d23

**Comment by JohnCoene** [comment]
This is also caused by the recent changes in the block ui: the remove button is rendered within `.block-tools` which is within the `.block-title` which is hidden when collapsed.

**Comment by JohnCoene** [comment]
Note: I also pushed a quick fix to the lock. I was importing/using the wrong function.

**Comment by JohnCoene** [comment]
Should be good to review/merge. I can look at any other issue in separate PRs

**Comment by JohnCoene** [comment]
Ready for review

**Review by DivadNojnarg — APPROVED** [review]
Remove button visibility will be fixed in another PR since not related to any change in this PR.

**Pull request merged**
