### PR TITLE
Options and Tweaks for key_value field

### PR DESCRIPTION
**Pull request by christophsax**
This should have no impact on non-server fields. The only exception is a `ignoreInit = FALSE` [change](https://github.com/blockr-org/blockr/pull/189/commits/e30b6f06f908fcfd9e7a617c2d8f6b833186a4e2), which is now needed for correct initialization.

### Improved `key_value field`

- Now uses `updateUI`, instead of `addUI` etc.
- Respects initialization value. E.g., if you define `new_filter2_block <- function(data, value = "Time == 2", ...) {`, this value would appear in a new block. That should make it work with serialization, too.
- Uses colnames from data
- Should be generally much more stable
- Adds 'filter2' block, as an expression-based alternative for our current filter block.

### CODE REVIEW

**Review by nbenn — APPROVED** [review]
As with #146, I don't think this is mature enough for merging. With that said, I'm not standing in your way.

**Comment by nbenn** [comment]
@christophsax a variant of the test case in https://github.com/blockr-org/blockr/pull/146#issuecomment-1879684292 (using new `keyvalue_field` arguments) is the following

```r
new_mutate_by_block <- function(data, ...) {

  handle_error <- function(e) {
    warning(e)
    expression()
  }

  parse_one <- function(x) {
    tryCatch(
      parse(text = x),
      error = handle_error
    )
  }

  parse_multiple <- function(x) {

    res <- lapply(x, parse_one)

    if (length(res)) {
      res <- do.call(c, res)
    }

    res
  }

  parse_cols <- function(new_cols) {
    parse_multiple(new_cols)
  }

  parse_grouping <- function(group_by) {
    res <- parse_multiple(group_by)
    names(res) <- NULL
    res
  }

  suggest_by <- function(data) colnames(data)[1L]

  fields <- list(
    new_cols = new_keyvalue_field(value = list()),
    group_by = new_keyvalue_field(suggest_by, multiple = FALSE, key = "none"),
    col_expr = new_hidden_field(parse_cols),
    grp_expr = new_hidden_field(parse_grouping)
  )

  expr <- quote(
    dplyr::mutate(..(col_expr), .by = c(..(grp_expr)))
  )

  new_block(
    fields = fields,
    expr = expr,
    ...,
    class = c("mutate_by_block", "transform_block")
  )
}

mutate_by_block <- function(data, ...) {
  initialize_block(new_mutate_by_block(data, ...), data)
}

generate_code_mutate_by_block <- function(x) {
  do.call(
    bquote,
    list(
      attr(x, "expr"),
      where = lapply(x, value),
      splice = TRUE
    )
  )
}

.S3method("generate_code", "mutate_by_block", generate_code_mutate_by_block)

eval_field <- function(x, env) {

  for (cmp in names(x)[lgl_ply(x, is.function)]) {
    fun <- x[[cmp]]
    value(x, cmp) <- do.call(fun, env[methods::formalArgs(fun)])
  }

  x
}

initialize_field_hidden_field <- function(x, env = list()) {
  validate_field(eval_field(x, env))
}

.S3method("initialize_field", "hidden_field", initialize_field_hidden_field)

serve_stack(new_stack(data_block, mutate_by_block))
```

**Comment by christophsax** [comment]
Thanks, will look at it.

**Comment by christophsax** [comment]
Abandoned in favor of #203

**Pull request closed without merging**
